name: Deploy

on:
  deployment:
  workflow_dispatch:
  push:
    branches:
      - master
      - production
    paths-ignore:
      - '**.md'

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: wearerequired/.github/.github/workflows/deploy.yml@v1-deploy-workflow
    secrets: inherit
